# Evaluación unidad 1 - Python avanzado

In [4]:
import re

El siguiente texto contiene datos de 

    - nombre, 

    - apellido, 

    - dirección postal, 

    - código postal, 

    - ciudad, 

    - país, 

    - teléfono y 

    - dirección de correo electrónico 

de varias personas.

In [5]:
data = 'Oliver Garcia, 789 Oak Avenue, 54321, Madrid, España, +34 91-123-4567, oliver.garcia@example.com\nBeatriz Ruiz, Carrer de Casanova 125, 08011, Barcelona, España, +34 936 789 012, beatriz.ruiz@email.com\nNoah Andersson, 123 Oak Street, 67890, Estocolmo, Suecia, +46 8-123-4567, noah.andersson@example.com\nCarmen Garcia, Rua dos Bacalhoeiros 10, 1100-071, Lisboa, Portugal, +351 21 567 8901, carmen.garcia@email.com\nJulia Saez, Rua da Prata 76, 1100-420, Lisboa, Portugal, +351 21 901 2345, julia.saez@email.com\nJavier Ruiz, Carrer de Balmes 90, 08008, Barcelona, España, +34 934 567 890, javier.ruiz@email.com\nRaul Lopez, Rua Garrett 8, 1200-203, Lisboa, Portugal, +351 21 678 9012, raul.lopez@email.com\nRuben Torres, Paseo del Prado 10, 28014, Madrid, España, +34 914 567 890, ruben.torres@email.com\nSophia Liu, 456 High Street, 67890, Shanghai, China, +86 21-1234-5678, sophia.liu@example.com\nCarla Jimenez, Rua Augusta 55, 1100-054, Lisboa, Portugal, +351 21 789 0123, carla.jimenez@email.com\nEmma Smith, 123 Main Street, 12345, Chicago, Estados Unidos, +1 555-123-4567, emma.smith@example.com\nDavid Fernandez, Rua das Flores 23, 1200-010, Lisboa, Portugal, +351 21 345 6789, david.fernandez@email.com\nAmelia Müller, 321 Lindenstrasse, 12345, Berlín, Alemania, +49 30-1234-5678, amelia.muller@example.com\nIsabel Jimenez, Carrer de la Ciutat de Granada 33, 08005, Barcelona, España, +34 931 234 567, isabel.jimenez@email.com\nMaria Torres, Gran Vía 32, 28013, Madrid, España, +34 912 345 678, maria.torres@email.com\nAdrian Sanchez, Carrer dels Tallers 23, 08001, Barcelona, España, +34 934 567 890, adrian.sanchez@email.com\nLiam Johnson, 789 Main Road, 54321, Sydney, Australia, +61 2-1234-5678, liam.johnson@example.com\nCarlos Ortiz, Rua de São Bento 201, 1200-821, Lisboa, Portugal, +351 21 345 6789, carlos.ortiz@email.com\nMarta Gonzalez, Rua do Comércio 67, 1000-250, Lisboa, Portugal, +351 21 234 5678, marta.gonzalez@email.com\nAna Perez, Calle Mayor 123, 28001, Madrid, España, +34 910 123 456, ana.perez@email.com\nJuan Hernandez, Calle Alcalá 123, 28009, Madrid, España, +34 910 987 654, juan.hernandez@email.com\nPaula Martin, Carrer del Mar 30, 08003, Barcelona, España, +34 933 456 789, paula.martin@email.com\nSara Gomez, Gran Via 56, 28013, Madrid, España, +34 911 111 111, sara.gomez@email.com\nSophie Dupont, 789 Rue Principale, 54321, París, Francia, +33 1-1234-5678, sophie.dupont@example.com\nElena Moreno, 456 Maple Street, 12345, México, México, +52 55-1234-5678, elena.moreno@example.com\nWilliam Martinez, 456 Main Street, 12345, Nueva York, Estados Unidos, +1 212-123-4567, william.martinez@example.com\nLuisa Rodriguez, Carrer Valencia 45, 08001, Barcelona, España, +34 932 234 567, luisa.rodriguez@email.com\nPablo Garcia, Plaza de España 1, 28008, Madrid, España, +34 913 456 789, pablo.garcia@email.com\nAva Chen, 789 Elm Avenue, 54321, Taipei, Taiwán, +886 2-1234-5678, ava.chen@example.com'

### Ejercicio 1 

Crear una función que reciba como parámetro el texto anterior y devuelva una lista. 

Cada elemento de esa lista debe ser otra lista con los campos de datos separados por comas de cada una de las personas.

Por ejemplo:

```python
[ 
    ['Oliver Garcia', '789 Oak Avenue', '54321', 'Madrid', 'España', '+34 91-123-4567', 'oliver.garcia@example.com'], 
    ...
]
```

In [6]:
#print(data)

In [7]:
#re.findall(r'\b[A-Za-z].*?\.com\b', data)
    # \b límite de palabra, asegura que las coincidencias comiencen con una letra
    # [A-Za-z] coincide con cualquier letra (mayúscula o minúscula)
    # .*? coincide con cualquier cantidad de caracteres (incluyendo letras, números, puntos, etc.), pero de manera no codiciosa, lo que significa que detendrá la coincidencia cuando encuentre '.com'.
    # \.com coincide con '.com' al final de la coincidencia.
    # \b límite de palabra, fin

In [8]:
def texto_a_datos(texto:str)->list:
    data = re.findall(r'\b[A-Za-z].*?\.com\b', texto)
    return [fila.split(', ') for fila in data]

lista_punto_2 = texto_a_datos(data)
print(lista_punto_2)

[['Oliver Garcia', '789 Oak Avenue', '54321', 'Madrid', 'España', '+34 91-123-4567', 'oliver.garcia@example.com'], ['Beatriz Ruiz', 'Carrer de Casanova 125', '08011', 'Barcelona', 'España', '+34 936 789 012', 'beatriz.ruiz@email.com'], ['Noah Andersson', '123 Oak Street', '67890', 'Estocolmo', 'Suecia', '+46 8-123-4567', 'noah.andersson@example.com'], ['Carmen Garcia', 'Rua dos Bacalhoeiros 10', '1100-071', 'Lisboa', 'Portugal', '+351 21 567 8901', 'carmen.garcia@email.com'], ['Julia Saez', 'Rua da Prata 76', '1100-420', 'Lisboa', 'Portugal', '+351 21 901 2345', 'julia.saez@email.com'], ['Javier Ruiz', 'Carrer de Balmes 90', '08008', 'Barcelona', 'España', '+34 934 567 890', 'javier.ruiz@email.com'], ['Raul Lopez', 'Rua Garrett 8', '1200-203', 'Lisboa', 'Portugal', '+351 21 678 9012', 'raul.lopez@email.com'], ['Ruben Torres', 'Paseo del Prado 10', '28014', 'Madrid', 'España', '+34 914 567 890', 'ruben.torres@email.com'], ['Sophia Liu', '456 High Street', '67890', 'Shanghai', 'China', '

### Ejercicio 2 

Dada la lista anterior, crear una función que separe el primer elemento de cada sub lista (nombre completo) en dos (nombre y apellido) y reemplace el elemento original por los dos nuevos elementos.

Por ejemplo: 

    'Oliver García' ---> 'Oliver', 'García'

El resto de los elementos de cada lista debe quedar igual.

Por ejemplo: 

```python
['Oliver Garcia', '789 Oak Avenue', '54321', 'Madrid', 'España', '+34 91-123-4567', 'oliver.garcia@example.com'] 
```
debe quedar:

```python
['Oliver', 'Garcia', '789 Oak Avenue', '54321', 'Madrid', 'España', '+34 91-123-4567', 'oliver.garcia@example.com']
```

In [9]:
def separar_nombre_apellido(lista:list)->list:
    for fila in lista:
        split_nombre_apellido = fila[0].split(' ')
        fila[0] = split_nombre_apellido[0]
        fila.insert(1, split_nombre_apellido[1])
    return lista

lista_punto_3 = separar_nombre_apellido(lista_punto_2)
print(lista_punto_3)

[['Oliver', 'Garcia', '789 Oak Avenue', '54321', 'Madrid', 'España', '+34 91-123-4567', 'oliver.garcia@example.com'], ['Beatriz', 'Ruiz', 'Carrer de Casanova 125', '08011', 'Barcelona', 'España', '+34 936 789 012', 'beatriz.ruiz@email.com'], ['Noah', 'Andersson', '123 Oak Street', '67890', 'Estocolmo', 'Suecia', '+46 8-123-4567', 'noah.andersson@example.com'], ['Carmen', 'Garcia', 'Rua dos Bacalhoeiros 10', '1100-071', 'Lisboa', 'Portugal', '+351 21 567 8901', 'carmen.garcia@email.com'], ['Julia', 'Saez', 'Rua da Prata 76', '1100-420', 'Lisboa', 'Portugal', '+351 21 901 2345', 'julia.saez@email.com'], ['Javier', 'Ruiz', 'Carrer de Balmes 90', '08008', 'Barcelona', 'España', '+34 934 567 890', 'javier.ruiz@email.com'], ['Raul', 'Lopez', 'Rua Garrett 8', '1200-203', 'Lisboa', 'Portugal', '+351 21 678 9012', 'raul.lopez@email.com'], ['Ruben', 'Torres', 'Paseo del Prado 10', '28014', 'Madrid', 'España', '+34 914 567 890', 'ruben.torres@email.com'], ['Sophia', 'Liu', '456 High Street', '678

### Ejericicio 3 

Crear una función que reciba por parámetro la **lista de datos de personas** creada en el ejercicio 2 y una **lista de claves** y devuelva una lista donde cada elemento sea un **diccionario**. 

Las **claves** de cada diccionario deben ser las de la lista 'claves' que se encuentra a continuación. 

```python
claves = ['nombre', 'apellido', 'direccion_postal', 'codigo_postal', 'ciudad', 'pais', 'telefono', 'mail']
```

Los **valores** correspondientes a cada clave deben ser los datos de cada usuario. 

Por ejemplo:

```python
[  
{'nombre': 'Oliver',  
  'apellido': 'Garcia',  
  'direccion_postal': '789 Oak Avenue',  
  'codigo_postal': '54321',  
  'ciudad': 'Madrid',  
  'pais': 'España',  
  'telefono': '+34 91-123-4567',  
  'mail': 'oliver.garcia@example.com'},  
  ...  
]
```

La lista debe contener tantos diccionarios como usuarios.

In [10]:
claves = ['nombre', 'apellido', 'direccion_postal', 'codigo_postal', 'ciudad', 'pais', 'telefono', 'mail']

In [11]:
def lista_a_diccionario(lista:list)->list:
    lista_diccionarios = []
    for fila in lista:
        lista_diccionarios.append(dict(zip(claves, fila)))
    return lista_diccionarios

lista_punto_4 = lista_a_diccionario(lista_punto_3)

lista_punto_4

[{'nombre': 'Oliver',
  'apellido': 'Garcia',
  'direccion_postal': '789 Oak Avenue',
  'codigo_postal': '54321',
  'ciudad': 'Madrid',
  'pais': 'España',
  'telefono': '+34 91-123-4567',
  'mail': 'oliver.garcia@example.com'},
 {'nombre': 'Beatriz',
  'apellido': 'Ruiz',
  'direccion_postal': 'Carrer de Casanova 125',
  'codigo_postal': '08011',
  'ciudad': 'Barcelona',
  'pais': 'España',
  'telefono': '+34 936 789 012',
  'mail': 'beatriz.ruiz@email.com'},
 {'nombre': 'Noah',
  'apellido': 'Andersson',
  'direccion_postal': '123 Oak Street',
  'codigo_postal': '67890',
  'ciudad': 'Estocolmo',
  'pais': 'Suecia',
  'telefono': '+46 8-123-4567',
  'mail': 'noah.andersson@example.com'},
 {'nombre': 'Carmen',
  'apellido': 'Garcia',
  'direccion_postal': 'Rua dos Bacalhoeiros 10',
  'codigo_postal': '1100-071',
  'ciudad': 'Lisboa',
  'pais': 'Portugal',
  'telefono': '+351 21 567 8901',
  'mail': 'carmen.garcia@email.com'},
 {'nombre': 'Julia',
  'apellido': 'Saez',
  'direccion_post

### Ejercicio 4

Crear una función que reciba como parámetro el diccionario anterior y devuelva una lista **sin repeticiones** de los países a los que pertenecen esas personas. Usar **list o set comprehensions**.

In [12]:
#lista_punto_4

In [13]:
def paises_distintos(lista:list)->list:
    paises_sin_repetir = list({diccionario['pais'] for diccionario in lista})
    return paises_sin_repetir

paises_distintos(lista_punto_4)


['China',
 'Australia',
 'Alemania',
 'Taiwán',
 'Portugal',
 'Suecia',
 'Francia',
 'México',
 'España',
 'Estados Unidos']

### Ejercicio 5 

Utilizando **list comprehensions** y **expresiones regulares**, crear una lista de números de teléfono sin guiones, espacios en blanco o cualquier otro caracter no numérico (por ejemplo, el signo '+').

Por ejemplo, 

```python
'+33 1-1234-5678' 
```

debe quedar 

```python
'33112345678'
```

In [14]:
#[re.sub(r'\D', '' ,diccionario['telefono']) for diccionario in lista_punto_4]

In [15]:
def telefonos_simplificados(lista:list)->list:
    return [re.sub(r'\D', '' ,diccionario['telefono']) for diccionario in lista]
    
telefonos_simplificados(lista_punto_4)

['34911234567',
 '34936789012',
 '4681234567',
 '351215678901',
 '351219012345',
 '34934567890',
 '351216789012',
 '34914567890',
 '862112345678',
 '351217890123',
 '15551234567',
 '351213456789',
 '493012345678',
 '34931234567',
 '34912345678',
 '34934567890',
 '61212345678',
 '351213456789',
 '351212345678',
 '34910123456',
 '34910987654',
 '34933456789',
 '34911111111',
 '33112345678',
 '525512345678',
 '12121234567',
 '34932234567',
 '34913456789',
 '886212345678']

### Ejercicio 6

Utilizando **list comprehensions** y **expresiones regulares**, crear una lista con los nombres y apellidos de aquellos usuarios que tengan una cuenta de mail del tipo `@email.com`

Resultado esperado:

```python
['Beatriz Ruiz', 'Carmen Garcia', 'Julia Saez', 'Javier Ruiz', 'Raul Lopez', 'Ruben Torres', 'Carla Jimenez', 'David Fernandez', 'Isabel Jimenez', 'Maria Torres', 'Adrian Sanchez', 'Carlos Ortiz', 'Marta Gonzalez', 'Ana Perez', 'Juan Hernandez', 'Paula Martin', 'Sara Gomez', 'Luisa Rodriguez', 'Pablo Garcia']
```

In [16]:
#[(diccionario['nombre'] + ' ' + diccionario['apellido'] + ' / ' + diccionario['mail']) for diccionario in lista_punto_4 if re.findall(r'@email\.com$', diccionario['mail'])] 

In [17]:
def lista_nombres_con_emailcom(lista:list)->list:
    return [(diccionario['nombre'] + ' ' +diccionario['apellido']) for diccionario in lista if re.findall(r'@email\.com$', diccionario['mail'])]
    
lista_nombres_con_emailcom(lista_punto_4)

['Beatriz Ruiz',
 'Carmen Garcia',
 'Julia Saez',
 'Javier Ruiz',
 'Raul Lopez',
 'Ruben Torres',
 'Carla Jimenez',
 'David Fernandez',
 'Isabel Jimenez',
 'Maria Torres',
 'Adrian Sanchez',
 'Carlos Ortiz',
 'Marta Gonzalez',
 'Ana Perez',
 'Juan Hernandez',
 'Paula Martin',
 'Sara Gomez',
 'Luisa Rodriguez',
 'Pablo Garcia']